
CREATE TABLE BANKS
(
  ID                  NUMBER(19)                NOT NULL,
  NAME                VARCHAR2(255 BYTE)        NOT NULL,
  CODE                VARCHAR2(255 BYTE)        NOT NULL,
  ACCOUNT             VARCHAR2(255 BYTE)        NOT NULL,
  CONTACTPERSON       VARCHAR2(255 BYTE),
  CONTACTPERSONEMAIL  VARCHAR2(255 BYTE),
  CONTACTPERSONPHONE  VARCHAR2(255 BYTE),
  CONTACTPERSONFAX    VARCHAR2(255 BYTE),
  ACTIVE              NUMBER(1)                 NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DECLARATIONS
(
  ID            NUMBER(19)                      NOT NULL,
  EXERCISE      VARCHAR2(255 BYTE),
  CUSTOMER      VARCHAR2(255 BYTE),
  REQUESTDATE   DATE,
  RECEIPTDATE   DATE,
  VALIDITYDATE  DATE,
  DECLARATION   NUMBER(1)                       NOT NULL,
  PASSPORT      NUMBER(1)                       NOT NULL,
  ACTIVE        NUMBER(1)                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DOCUMENT_INVOICES
(
  DOCUMENT_ID  NUMBER(19)                       NOT NULL,
  INVOICE_ID   NUMBER(19)                       NOT NULL,
  CREATEDDATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EXERCISES
(
  ID                   NUMBER(19)               NOT NULL,
  VERSION              NUMBER(10)               NOT NULL,
  YEAR                 NUMBER(10)               NOT NULL,
  STATUS               VARCHAR2(255 BYTE),
  STARTDATE            DATE,
  ENDDATE              DATE,
  ISAPPPROVED          NUMBER(1)                NOT NULL,
  TOT_EXP_AMOUNT       FLOAT(126)               NOT NULL,
  INFLATIONPERCENTAGE  FLOAT(126)               NOT NULL,
  TOT_REP_AMOUNT       FLOAT(126)               NOT NULL,
  TOT_REAL_AMOUNT      FLOAT(126)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ORIGINS
(
  ID    NUMBER(19)                              NOT NULL,
  NAME  VARCHAR2(255 BYTE)                      NOT NULL,
  CODE  VARCHAR2(255 BYTE)                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROFILES
(
  ID        NUMBER(19)                          NOT NULL,
  VERSION   NUMBER(10)                          NOT NULL,
  NAME      VARCHAR2(255 BYTE),
  FROMDATE  DATE,
  TODATE    DATE,
  ACTIVE    NUMBER(1)                           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE RIGHTS
(
  ID           NUMBER(19)                       NOT NULL,
  NAME         VARCHAR2(255 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE),
  CODE         VARCHAR2(255 BYTE),
  TYPE         VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TASKS
(
  ID              NUMBER(19)                    NOT NULL,
  NAME            VARCHAR2(255 BYTE),
  DESCRIPTION     VARCHAR2(255 BYTE),
  CODEPRESTATION  VARCHAR2(255 BYTE),
  CHARGEABLE      NUMBER(1)                     NOT NULL,
  CODE            VARCHAR2(255 BYTE),
  VERSION         NUMBER(10)                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EMPLOYEES
(
  ID              NUMBER(19)                    NOT NULL,
  VERSION         NUMBER(10)                    NOT NULL,
  USERNAME        VARCHAR2(255 BYTE),
  FIRSTNAME       VARCHAR2(255 BYTE),
  LASTNAME        VARCHAR2(255 BYTE),
  JOBTITLE        VARCHAR2(255 BYTE),
  COUNTRY         VARCHAR2(255 BYTE),
  PHONE           VARCHAR2(255 BYTE),
  MOBILE          VARCHAR2(255 BYTE),
  PERSONALPHONE   VARCHAR2(255 BYTE),
  PERSONALMOBILE  VARCHAR2(255 BYTE),
  EMAIL           VARCHAR2(255 BYTE),
  WEBADDRESS      VARCHAR2(255 BYTE),
  PHOTO           VARCHAR2(255 BYTE),
  CODE            VARCHAR2(255 BYTE),
  ACTIVE          NUMBER(1),
  PASSWORD        VARCHAR2(255 BYTE),
  LOGIN           VARCHAR2(255 BYTE),
  UPDATEUSER      VARCHAR2(255 BYTE),
  DATE_OF_BIRTH   DATE,
  CREATEDATE      DATE,
  MODIFIEDDATE    DATE,
  ADDRESS         VARCHAR2(255 BYTE),
  PRIXVENTE       FLOAT(126)                    NOT NULL,
  PRIXREVIENT     FLOAT(126)                    NOT NULL,
  COUTHORAIRE     FLOAT(126)                    NOT NULL,
  FK_POSITION     NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EXERCISE_OBJECTIFS
(
  ID              NUMBER(19)                    NOT NULL,
  TAUX            FLOAT(126),
  ANNUAL          FLOAT(126),
  ANNUAL_CO       FLOAT(126),
  ROLE            VARCHAR2(255 BYTE),
  FK_RESPONSABLE  NUMBER(19)                    NOT NULL,
  FK_EXERCISE     NUMBER(19)                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EXERCISE_RESULTS
(
  ID              NUMBER(19)                    NOT NULL,
  JAN             FLOAT(126),
  FEB             FLOAT(126),
  MAR             FLOAT(126),
  APR             FLOAT(126),
  MAY             FLOAT(126),
  JUN             FLOAT(126),
  JUL             FLOAT(126),
  AUG             FLOAT(126),
  SEP             FLOAT(126),
  OCT             FLOAT(126),
  NOV             FLOAT(126),
  DEC             FLOAT(126),
  ROLE            VARCHAR2(255 BYTE),
  FK_EXERCISE     NUMBER(19)                    NOT NULL,
  FK_RESPONSABLE  NUMBER(19)                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIMESHEETS
(
  ID               NUMBER(19)                   NOT NULL,
  VERSION          NUMBER(10)                   NOT NULL,
  EXERCISE         VARCHAR2(255 BYTE),
  CREATEDATE       DATE                         NOT NULL,
  UPDATEDATE       DATE,
  ACCEPTEDDATE     DATE,
  REJECTEDDATE     DATE,
  SUBMITDATE       DATE,
  VALIDATIONDATE   DATE,
  STARTDATEOFWEEK  DATE,
  ENDDATEOFWEEK    DATE,
  STATUS           VARCHAR2(255 BYTE),
  WEEKNUMBER       NUMBER(10)                   NOT NULL,
  FK_EMPLOYEE      NUMBER(19),
  USERID           NUMBER(19)                   NOT NULL,
  PRIXVENTE        FLOAT(126),
  PRIXREVIENT      FLOAT(126),
  COUTHORAIRE      FLOAT(126)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TRAININGS
(
  ID               NUMBER(19)                   NOT NULL,
  TITLE            VARCHAR2(255 BYTE)           NOT NULL,
  DESCRIPTION      VARCHAR2(255 BYTE)           NOT NULL,
  STARTDATE        DATE                         NOT NULL,
  ENDDATE          DATE                         NOT NULL,
  COMPANYNAME      VARCHAR2(255 BYTE)           NOT NULL,
  BENEFICIAIRE_ID  NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ACCESS_RIGHTS
(
  ID           NUMBER(19)                       NOT NULL,
  ACTIVE       NUMBER(1)                        NOT NULL,
  FK_RIGHT     NUMBER(19)                       NOT NULL,
  FK_EMPLOYEE  NUMBER(19)                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CUSTOMERS
(
  ID                  NUMBER(19)                NOT NULL,
  WEB_ADDRESS         VARCHAR2(255 BYTE),
  ACTIVE              NUMBER(1)                 NOT NULL,
  COUNTRY             VARCHAR2(255 BYTE),
  MAINADDRESS         VARCHAR2(255 BYTE),
  MAINBILLINGADDRESS  VARCHAR2(255 BYTE),
  ACTIVITY            VARCHAR2(255 BYTE),
  CREATEDATE          DATE,
  UPDATEDATE          DATE,
  UPDATEDUSER         VARCHAR2(255 BYTE),
  COMPY_NAME          VARCHAR2(255 BYTE),
  FAX                 VARCHAR2(255 BYTE),
  PHONE               VARCHAR2(255 BYTE),
  MOBILE              VARCHAR2(255 BYTE),
  P_PHONE             VARCHAR2(255 BYTE),
  P_MOBILE            VARCHAR2(255 BYTE),
  EMAIL               VARCHAR2(255 BYTE),
  CODE                VARCHAR2(255 BYTE)        NOT NULL,
  VERSION             NUMBER(10)                NOT NULL,
  FK_ORIGIN           NUMBER(19),
  FK_MANAGER          NUMBER(19)                NOT NULL,
  FK_ASSOCIE          NUMBER(19)                NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DOCUMENTS
(
  ID           NUMBER(19)                       NOT NULL,
  FILE_NAME    VARCHAR2(255 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE),
  CREATEDATE   DATE,
  UPDATEDATE   DATE,
  TITLE        VARCHAR2(255 BYTE),
  VERSION      NUMBER(10)                       NOT NULL,
  OWNER        NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTACTS
(
  ID           NUMBER(19)                       NOT NULL,
  NAME         VARCHAR2(255 BYTE)               NOT NULL,
  F_NAME       VARCHAR2(255 BYTE)               NOT NULL,
  L_NAME       VARCHAR2(255 BYTE)               NOT NULL,
  JOB          VARCHAR2(255 BYTE),
  B_PHONE      VARCHAR2(255 BYTE),
  B_MOBILE     VARCHAR2(255 BYTE),
  B_FAX        VARCHAR2(255 BYTE),
  P_PHONE      VARCHAR2(255 BYTE)               NOT NULL,
  P_MOBILE     VARCHAR2(255 BYTE),
  B_EMAIL      VARCHAR2(255 BYTE),
  P_EMAIL      VARCHAR2(255 BYTE),
  B_WEB_ADDR   VARCHAR2(255 BYTE),
  ACTIVE       NUMBER(1)                        NOT NULL,
  B_ACTIVITY   VARCHAR2(255 BYTE),
  UPDATEDUSER  VARCHAR2(255 BYTE),
  COMPANY      VARCHAR2(255 BYTE)               NOT NULL,
  ADDRESS      VARCHAR2(255 BYTE),
  CREATEDATE   DATE,
  UPDATEDATE   DATE,
  VERSION      NUMBER(10)                       NOT NULL,
  FK_CUSTOMER  NUMBER(19)                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTRACTS
(
  ID           NUMBER(19)                       NOT NULL,
  REFERENCE    VARCHAR2(255 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE),
  FROMDATE     DATE,
  TODATE       DATE,
  DURATION     NUMBER(10),
  LANGUAGE     VARCHAR2(255 BYTE),
  VAL          FLOAT(126)                       NOT NULL,
  CUR          VARCHAR2(255 BYTE)               NOT NULL,
  VERSION      NUMBER(10)                       NOT NULL,
  MISSIONTYPE  VARCHAR2(255 BYTE)               NOT NULL,
  AGREED       NUMBER(1),
  FK_CUSTOMER  NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE BUDGETS
(
  ID           NUMBER(19)                       NOT NULL,
  VERSION      NUMBER(10)                       NOT NULL,
  EXP_AMOUNT   FLOAT(126)                       NOT NULL,
  REAL_AMOUNT  FLOAT(126),
  REP_AMOUNT   FLOAT(126),
  COMMENTS     VARCHAR2(255 BYTE),
  STATUS       VARCHAR2(255 BYTE),
  FK_ASSOCIE   NUMBER(19)                       NOT NULL,
  FK_CONTRACT  NUMBER(19)                       NOT NULL,
  FK_EXERCISE  NUMBER(19)                       NOT NULL,
  FK_MANAGER   NUMBER(19)                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MISSIONS
(
  ID                  NUMBER(19)                NOT NULL,
  EXERCISE            VARCHAR2(255 BYTE),
  TITLE               VARCHAR2(255 BYTE),
  REFER               VARCHAR2(255 BYTE)        NOT NULL,
  COMMENTS            VARCHAR2(255 BYTE)        NOT NULL,
  CREATEDATE          DATE                      NOT NULL,
  STARTDATE           DATE,
  DUEDATE             DATE,
  UPDATEDATE          DATE,
  UPDATEDUSER         VARCHAR2(255 BYTE),
  STATUS              VARCHAR2(255 BYTE),
  TYP                 VARCHAR2(255 BYTE)        NOT NULL,
  TOTALCOST           FLOAT(126),
  TOTALSCHEDULEDCOST  FLOAT(126),
  COUNTSCHEDULEDDAYS  NUMBER(10)                NOT NULL,
  VERSION             NUMBER(10)                NOT NULL,
  LANGUAGE            VARCHAR2(255 BYTE),
  ANNUALBUDGET_ID     NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ACTIVITIES
(
  ID           NUMBER(19)                       NOT NULL,
  STATUS       VARCHAR2(255 BYTE),
  TODO         VARCHAR2(255 BYTE),
  VERSION      NUMBER(10)                       NOT NULL,
  STARTDATE    DATE                             NOT NULL,
  UPDATEDATE   DATE,
  ENDDATE      DATE,
  MISSION_ID   NUMBER(19),
  FK_EMPLOYEE  NUMBER(19)                       NOT NULL,
  COMMENTS     VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DOCS_MISSIONS
(
  ID_MISSION   NUMBER(19)                       NOT NULL,
  ID_DOCUMENT  NUMBER(19)                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EVENTS
(
  ID           NUMBER(19)                       NOT NULL,
  YEAR         NUMBER(10)                       NOT NULL,
  MONTH        NUMBER(10)                       NOT NULL,
  DAY          NUMBER(10)                       NOT NULL,
  STARTHOUR    NUMBER(10)                       NOT NULL,
  ENDHOUR      NUMBER(10)                       NOT NULL,
  TYPE         VARCHAR2(255 BYTE),
  TITLE        VARCHAR2(255 BYTE),
  DATEOFEVENT  DATE,
  FK_EMPLOYEE  NUMBER(19)                       NOT NULL,
  FK_MISSION   NUMBER(19),
  PRIXVENTE    FLOAT(126),
  PRIXREVIENT  FLOAT(126),
  COUTHORAIRE  FLOAT(126)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE INVOICES
(
  DTYPE             VARCHAR2(31 BYTE)           NOT NULL,
  ID                NUMBER(19)                  NOT NULL,
  VERSION           NUMBER(10)                  NOT NULL,
  TYPE              VARCHAR2(255 BYTE),
  DATEFACTURE       DATE,
  SENTDATE          DATE,
  DATEOFPAYMENT     DATE,
  CURRENCY          VARCHAR2(3 BYTE)            NOT NULL,
  YEAR              VARCHAR2(255 BYTE)          NOT NULL,
  LIBELLE           VARCHAR2(255 BYTE)          NOT NULL,
  AMOUNT            FLOAT(126)                  NOT NULL,
  REFERENCE         VARCHAR2(255 BYTE)          NOT NULL,
  STATUS            VARCHAR2(255 BYTE),
  TOTALWORKEDHOURS  FLOAT(126),
  TOTALADVANCES     FLOAT(126),
  TOTALEXTRACOSTS   FLOAT(126),
  FINALBILL_ID      NUMBER(19),
  PROJECT_ID        NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MESSAGE
(
  ID          NUMBER(19)                        NOT NULL,
  SUBJECT     VARCHAR2(255 BYTE),
  CONTENTS    VARCHAR2(255 BYTE),
  CREATEDATE  DATE,
  MISSION_ID  NUMBER(19),
  FROM_ID     NUMBER(19),
  TO_ID       NUMBER(19),
  PARENT_ID   NUMBER(19),
  SENTDATE    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MISSION_COSTS
(
  ID            NUMBER(19)                      NOT NULL,
  VERSION       NUMBER(10)                      NOT NULL,
  COSTCODE      VARCHAR2(255 BYTE),
  DESCRIPTION   VARCHAR2(255 BYTE),
  AMOUNT        FLOAT(126)                      NOT NULL,
  CURRENCY      VARCHAR2(3 BYTE)                NOT NULL,
  CREATEDATE    DATE,
  FINALBILL_ID  NUMBER(19),
  OWNER_ID      NUMBER(19),
  MISSION_ID    NUMBER(19)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PAYMENTS
(
  ID            NUMBER(19)                      NOT NULL,
  CODE          VARCHAR2(255 BYTE)              NOT NULL,
  REFERENCE     VARCHAR2(255 BYTE)              NOT NULL,
  CUSTOMERNAME  VARCHAR2(255 BYTE)              NOT NULL,
  AMOUNT        FLOAT(126)                      NOT NULL,
  CURRENCY      VARCHAR2(3 BYTE)                NOT NULL,
  PAYMENTDATE   DATE                            NOT NULL,
  VERSION       NUMBER(10)                      NOT NULL,
  FK_FACTURE    NUMBER(19)                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIMESHEET_ROWS
(
  ID              NUMBER(19)                    NOT NULL,
  VERSION         NUMBER(10)                    NOT NULL,
  FK_TIMESHEET    NUMBER(19)                    NOT NULL,
  FK_ACTIVITY     NUMBER(19),
  LABEL           VARCHAR2(255 BYTE),
  CODEPRESTATION  VARCHAR2(255 BYTE),
  CUSTNUMBER      VARCHAR2(255 BYTE),
  ASSCODE         VARCHAR2(255 BYTE),
  MANCODE         VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DOCS_INVOICES
(
  ID_INVOICE   NUMBER(19)                       NOT NULL,
  ID_DOCUMENT  NUMBER(19)                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE INVOICE_REMINDS
(
  ID          NUMBER(19)                        NOT NULL,
  REMINDDATE  DATE,
  VERSION     NUMBER(10)                        NOT NULL,
  FK_FACTURE  NUMBER(19)                        NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIMESHEET_CELLS
(
  ID         NUMBER(19)                         NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  DAYNUMBER  NUMBER(10),
  VALUE      FLOAT(126)                         NOT NULL,
  FK_ROW     NUMBER(19)                         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BANKS ADD (
  PRIMARY KEY (ID));

ALTER TABLE BANKS ADD (
  UNIQUE (NAME));

ALTER TABLE BANKS ADD (
  UNIQUE (CODE));

ALTER TABLE BANKS ADD (
  UNIQUE (ACCOUNT));


ALTER TABLE DECLARATIONS ADD (
  PRIMARY KEY (ID));


ALTER TABLE DOCUMENT_INVOICES ADD (
  PRIMARY KEY (DOCUMENT_ID, INVOICE_ID));


ALTER TABLE EXERCISES ADD (
  PRIMARY KEY (ID));

ALTER TABLE EXERCISES ADD (
  UNIQUE (YEAR));


ALTER TABLE ORIGINS ADD (
  PRIMARY KEY (ID));

ALTER TABLE ORIGINS ADD (
  UNIQUE (CODE));


ALTER TABLE PROFILES ADD (
  PRIMARY KEY (ID));


ALTER TABLE RIGHTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE TASKS ADD (
  PRIMARY KEY (ID));


ALTER TABLE EMPLOYEES ADD (
  PRIMARY KEY (ID));

ALTER TABLE EMPLOYEES ADD (
  UNIQUE (LOGIN));


ALTER TABLE EXERCISE_OBJECTIFS ADD (
  PRIMARY KEY (ID));


ALTER TABLE EXERCISE_RESULTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE TIMESHEETS ADD (
  PRIMARY KEY (ID));


ALTER TABLE TRAININGS ADD (
  PRIMARY KEY (ID));


ALTER TABLE ACCESS_RIGHTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE CUSTOMERS ADD (
  PRIMARY KEY (ID));

ALTER TABLE CUSTOMERS ADD (
  UNIQUE (COMPY_NAME));

ALTER TABLE CUSTOMERS ADD (
  UNIQUE (CODE));


ALTER TABLE DOCUMENTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE CONTACTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE CONTRACTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE BUDGETS ADD (
  PRIMARY KEY (ID));


ALTER TABLE MISSIONS ADD (
  PRIMARY KEY (ID));


ALTER TABLE ACTIVITIES ADD (
  PRIMARY KEY (ID));


ALTER TABLE DOCS_MISSIONS ADD (
  PRIMARY KEY (ID_MISSION, ID_DOCUMENT));


ALTER TABLE EVENTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE INVOICES ADD (
  PRIMARY KEY (ID));

ALTER TABLE INVOICES ADD (
  UNIQUE (REFERENCE));


ALTER TABLE MESSAGE ADD (
  PRIMARY KEY (ID));


ALTER TABLE MISSION_COSTS ADD (
  PRIMARY KEY (ID));


ALTER TABLE PAYMENTS ADD (
  PRIMARY KEY (ID));

ALTER TABLE PAYMENTS ADD (
  UNIQUE (REFERENCE));


ALTER TABLE TIMESHEET_ROWS ADD (
  PRIMARY KEY (ID));


ALTER TABLE INVOICE_REMINDS ADD (
  PRIMARY KEY (ID));


ALTER TABLE TIMESHEET_CELLS ADD (
  PRIMARY KEY (ID));


ALTER TABLE EMPLOYEES ADD (
  CONSTRAINT FK4351FF65A24E0AD9 FOREIGN KEY (FK_POSITION) 
    REFERENCES PROFILES (ID));


ALTER TABLE EXERCISE_OBJECTIFS ADD (
  CONSTRAINT FKFF84459015411C7F FOREIGN KEY (FK_RESPONSABLE) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE EXERCISE_OBJECTIFS ADD (
  CONSTRAINT FKFF8445903E4ADC37 FOREIGN KEY (FK_EXERCISE) 
    REFERENCES EXERCISES (ID));


ALTER TABLE EXERCISE_RESULTS ADD (
  CONSTRAINT FK923A086F15411C7F FOREIGN KEY (FK_RESPONSABLE) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE EXERCISE_RESULTS ADD (
  CONSTRAINT FK923A086F3E4ADC37 FOREIGN KEY (FK_EXERCISE) 
    REFERENCES EXERCISES (ID));


ALTER TABLE TIMESHEETS ADD (
  CONSTRAINT FK821E8001D76EA5E3 FOREIGN KEY (FK_EMPLOYEE) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE TIMESHEETS ADD (
  CONSTRAINT FK821E8001EB403F21 FOREIGN KEY (USERID) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE TRAININGS ADD (
  CONSTRAINT FKDC0922B960E76277 FOREIGN KEY (BENEFICIAIRE_ID) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE ACCESS_RIGHTS ADD (
  CONSTRAINT FK541E311220F5D111 FOREIGN KEY (FK_RIGHT) 
    REFERENCES RIGHTS (ID));

ALTER TABLE ACCESS_RIGHTS ADD (
  CONSTRAINT FK541E3112D76EA5E3 FOREIGN KEY (FK_EMPLOYEE) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE CUSTOMERS ADD (
  CONSTRAINT FK6268C35294B3B2E FOREIGN KEY (FK_MANAGER) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE CUSTOMERS ADD (
  CONSTRAINT FK6268C35CD847372 FOREIGN KEY (FK_ASSOCIE) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE CUSTOMERS ADD (
  CONSTRAINT FK6268C35F486AC93 FOREIGN KEY (FK_ORIGIN) 
    REFERENCES ORIGINS (ID));


ALTER TABLE DOCUMENTS ADD (
  CONSTRAINT FKDE5562982368FFAE FOREIGN KEY (OWNER) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE CONTACTS ADD (
  CONSTRAINT FKCD35053916BD843 FOREIGN KEY (FK_CUSTOMER) 
    REFERENCES CUSTOMERS (ID));


ALTER TABLE CONTRACTS ADD (
  CONSTRAINT FK8E852181916BD843 FOREIGN KEY (FK_CUSTOMER) 
    REFERENCES CUSTOMERS (ID));


ALTER TABLE BUDGETS ADD (
  CONSTRAINT FK3846C5AE294B3B2E FOREIGN KEY (FK_MANAGER) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE BUDGETS ADD (
  CONSTRAINT FK3846C5AE3E4ADC37 FOREIGN KEY (FK_EXERCISE) 
    REFERENCES EXERCISES (ID));

ALTER TABLE BUDGETS ADD (
  CONSTRAINT FK3846C5AE592FAAB FOREIGN KEY (FK_CONTRACT) 
    REFERENCES CONTRACTS (ID));

ALTER TABLE BUDGETS ADD (
  CONSTRAINT FK3846C5AECD847372 FOREIGN KEY (FK_ASSOCIE) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE MISSIONS ADD (
  CONSTRAINT FKE6B7A0679BED1B27 FOREIGN KEY (ANNUALBUDGET_ID) 
    REFERENCES BUDGETS (ID));


ALTER TABLE ACTIVITIES ADD (
  CONSTRAINT FK970527ED8B5ED24D FOREIGN KEY (MISSION_ID) 
    REFERENCES MISSIONS (ID));

ALTER TABLE ACTIVITIES ADD (
  CONSTRAINT FK970527EDD76EA5E3 FOREIGN KEY (FK_EMPLOYEE) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE DOCS_MISSIONS ADD (
  CONSTRAINT FKD26709EB7A20C807 FOREIGN KEY (ID_MISSION) 
    REFERENCES MISSIONS (ID));

ALTER TABLE DOCS_MISSIONS ADD (
  CONSTRAINT FKD26709EBC08E7B27 FOREIGN KEY (ID_DOCUMENT) 
    REFERENCES DOCUMENTS (ID));


ALTER TABLE EVENTS ADD (
  CONSTRAINT FK7A9AD519AB237DB1 FOREIGN KEY (FK_MISSION) 
    REFERENCES MISSIONS (ID));

ALTER TABLE EVENTS ADD (
  CONSTRAINT FK7A9AD519D76EA5E3 FOREIGN KEY (FK_EMPLOYEE) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE INVOICES ADD (
  CONSTRAINT FK549812E61B8C81A0 FOREIGN KEY (PROJECT_ID) 
    REFERENCES MISSIONS (ID));

ALTER TABLE INVOICES ADD (
  CONSTRAINT FK549812E6B050AAC1 FOREIGN KEY (FINALBILL_ID) 
    REFERENCES INVOICES (ID));


ALTER TABLE MESSAGE ADD (
  CONSTRAINT FK63B68BE723AB9A5A FOREIGN KEY (TO_ID) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE MESSAGE ADD (
  CONSTRAINT FK63B68BE758B0CEA FOREIGN KEY (PARENT_ID) 
    REFERENCES MESSAGE (ID));

ALTER TABLE MESSAGE ADD (
  CONSTRAINT FK63B68BE78B5ED24D FOREIGN KEY (MISSION_ID) 
    REFERENCES MISSIONS (ID));

ALTER TABLE MESSAGE ADD (
  CONSTRAINT FK63B68BE7F9A84ECB FOREIGN KEY (FROM_ID) 
    REFERENCES EMPLOYEES (ID));


ALTER TABLE MISSION_COSTS ADD (
  CONSTRAINT FK831F01938036AB22 FOREIGN KEY (OWNER_ID) 
    REFERENCES EMPLOYEES (ID));

ALTER TABLE MISSION_COSTS ADD (
  CONSTRAINT FK831F01938B5ED24D FOREIGN KEY (MISSION_ID) 
    REFERENCES MISSIONS (ID));

ALTER TABLE MISSION_COSTS ADD (
  CONSTRAINT FK831F0193B050AAC1 FOREIGN KEY (FINALBILL_ID) 
    REFERENCES INVOICES (ID));


ALTER TABLE PAYMENTS ADD (
  CONSTRAINT FK810FFF2D5F680542 FOREIGN KEY (FK_FACTURE) 
    REFERENCES INVOICES (ID));


ALTER TABLE TIMESHEET_ROWS ADD (
  CONSTRAINT FK4FBC2B6683C0BEA5 FOREIGN KEY (FK_ACTIVITY) 
    REFERENCES ACTIVITIES (ID));

ALTER TABLE TIMESHEET_ROWS ADD (
  CONSTRAINT FK4FBC2B66E279BDBD FOREIGN KEY (FK_TIMESHEET) 
    REFERENCES TIMESHEETS (ID));


ALTER TABLE DOCS_INVOICES ADD (
  CONSTRAINT FK40477C6AC08E7B27 FOREIGN KEY (ID_DOCUMENT) 
    REFERENCES DOCUMENTS (ID));

ALTER TABLE DOCS_INVOICES ADD (
  CONSTRAINT FK40477C6AE4504B49 FOREIGN KEY (ID_INVOICE) 
    REFERENCES INVOICES (ID));


ALTER TABLE INVOICE_REMINDS ADD (
  CONSTRAINT FK4448E4BC5F680542 FOREIGN KEY (FK_FACTURE) 
    REFERENCES INVOICES (ID));


ALTER TABLE TIMESHEET_CELLS ADD (
  CONSTRAINT FKA6F12B44472A6CF5 FOREIGN KEY (FK_ROW) 
    REFERENCES TIMESHEET_ROWS (ID));



